// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vliipymofvhkewtlyqdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaWlweW1vZnZoa2V3dGx5cWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNTEyMzksImV4cCI6MjA0OTYyNzIzOX0.d_heyFGQQgl_vLqUncG3u87cTq_cptgPk2dwaBIurek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);